CREATE TABLE CC_CMCD_REG_TC
(
    DICT_SEQNO    NUMBER(3)  NOT NULL , --용어 일련번호
    ENG_DICT_NM   VARCHAR2(50)  NOT NULL , --영어용어명
    CD_VALUE      VARCHAR2(20)  NOT NULL , --코드값
    CD_SEQNO      NUMBER(3)  NOT NULL , -- 코드일련번호
    CD_VALUE_NM   VARCHAR2(100)  NOT NULL , --코드값명
    CD_VALUE_DESC_CONT  VARCHAR2(500)  NULL , --코드값 설명내용
    HIGH_ENG_DICT_NM  VARCHAR2(50)  NULL , --상위영어용어명
    HIGH_DICT_SEQNO   NUMBER(3)  NULL , --상위영어용어명
    HIGH_CD_VALUE     VARCHAR2(20)  NULL , --상위코드값
    HIGH_CD_SEQNO     NUMBER(3)  NULL , -- 상위코드일련번호
    SCR_ORDR      NUMBER(3)  NOT NULL , --화면순서
    USE_YN        CHAR(1)  NOT NULL , --사용여부
    STDZ_REG_TPCD     CHAR(1)  NULL , --표준화 등록 구분코드(등록,수정,삭제)
    STDZ_PROC_TPCD    CHAR(1)  NOT NULL , --표준화 처리구분코드(미처리,승인,거부)
    REG_TM        VARCHAR2(14)  NOT NULL , --등록일시
    REGT_NM       VARCHAR2(50)  NOT NULL , --등록자 명
    PROC_TM       VARCHAR2(14)  NULL , --처리 일시
    PROCR_NM      VARCHAR2(50)  NULL , --처리자 명
    ERR_CONT      VARCHAR2(500)  NULL -- 오류내용
);
CREATE UNIQUE INDEX CC_CMCD_REG_TC_PK ON CC_CMCD_REG_TC
    (DICT_SEQNO  ASC,ENG_DICT_NM  ASC,CD_VALUE  ASC,CD_SEQNO  ASC);

ALTER TABLE CC_CMCD_REG_TC
    ADD CONSTRAINT  CC_CMCD_REG_TC_PK PRIMARY KEY (DICT_SEQNO,ENG_DICT_NM,CD_VALUE,CD_SEQNO);

CREATE INDEX CC_CMCD_REG_TC_IX2 ON CC_CMCD_REG_TC
    (HIGH_CD_VALUE  ASC,HIGH_ENG_DICT_NM  ASC,HIGH_DICT_SEQNO  ASC,HIGH_CD_SEQNO  ASC);


CREATE TABLE CC_CMCD_TC
(
    ENG_DICT_NM   VARCHAR2(50)  NOT NULL , --영문용어명
    CD_VALUE      CHAR(20)  NOT NULL ,
    HIGH_ENG_DICT_NM  VARCHAR2(50)  NULL ,
    HIGH_CD_VALUE     CHAR(20)  NULL ,
    CD_VALUE_NM   VARCHAR2(50)  NOT NULL ,
    CD_VALUE_DESC_CONT  VARCHAR2(500)  NULL ,
    SCR_ORDR      NUMBER(3)  NULL ,
    USE_YN        CHAR(1)  NULL , --사용여부
    MODF_TM       VARCHAR2(14)  NULL , -- 수정시각
    MODFR_NM      VARCHAR2(50)  NULL   -- 수정자명
);
CREATE UNIQUE INDEX CC_CMCD_TC_PK ON CC_CMCD_TC
    (ENG_DICT_NM  ASC,CD_VALUE  ASC);

ALTER TABLE CC_CMCD_TC
    ADD CONSTRAINT  CC_CMCD_TC_PK PRIMARY KEY (ENG_DICT_NM,CD_VALUE);



CREATE TABLE CC_DICT_REG_TC
(
    ENG_DICT_NM   VARCHAR2(50)  NOT NULL ,
    DICT_SEQNO    NUMBER(3)  NOT NULL ,   -- 용어일련번호
    DICT_NM       VARCHAR2(100)  NOT NULL , -- 용어명
    DICT_SCR_NM   VARCHAR2(100)  NULL , -- 용어화면명
    CMNCD_YN      CHAR(1)  NULL , --공통코드여부
    DOMAIN_ID     VARCHAR2(10)  NOT NULL , --도메인ID
    DOMAIN_SEQNO      NUMBER(3)  NOT NULL , --도메인일련번호
    USE_YN        CHAR(1)  NOT NULL ,
    STDZ_REG_TPCD     CHAR(1)  NULL ,
    STDZ_PROC_TPCD    CHAR(1)  NULL ,
    REG_TM        VARCHAR2(14)  NOT NULL ,
    REGT_NM       VARCHAR2(50)  NOT NULL ,
    PROC_TM       VARCHAR2(14)  NULL ,
    PROCR_NM      VARCHAR2(50)  NULL ,
    ERR_CONT      VARCHAR2(500)  NULL
);
CREATE UNIQUE INDEX CC_DICT_REG_TC_PK ON CC_DICT_REG_TC
    (ENG_DICT_NM  ASC,DICT_SEQNO  ASC);

ALTER TABLE CC_DICT_REG_TC
    ADD CONSTRAINT  CC_DICT_REG_TC_PK PRIMARY KEY (ENG_DICT_NM,DICT_SEQNO);

CREATE TABLE CC_DICT_TC
(
    ENG_DICT_NM   VARCHAR2(50)  NOT NULL ,
    DICT_NM       VARCHAR2(100)  NOT NULL ,
    DICT_SCR_NM   VARCHAR2(100)  NULL ,
    CMNCD_YN      CHAR(1)  NULL ,
    DOMAIN_ID     VARCHAR2(10)  NOT NULL ,
    USE_YN        CHAR(1)  NOT NULL ,
    MODF_TM       VARCHAR2(14)  NOT NULL ,
    MODFR_NM      VARCHAR2(50)  NOT NULL
);

CREATE UNIQUE INDEX CC_DICT_TC_PK ON CC_DICT_TC
    (ENG_DICT_NM  ASC);

ALTER TABLE CC_DICT_TC
    ADD CONSTRAINT  CC_DICT_TC_PK PRIMARY KEY (ENG_DICT_NM);

CREATE INDEX CC_DICT_TC_IX1 ON CC_DICT_TC
    (DOMAIN_ID  ASC);


CREATE TABLE CC_DOMAIN_REG_TC
(
    DOMAIN_ID     VARCHAR2(10)  NOT NULL , --도메인ID
    DOMAIN_SEQNO      NUMBER(3)  NOT NULL , --도메인일련번호
    DOMAIN_NM     VARCHAR2(50)  NOT NULL , --도메인명
    DOMAIN_DESC_CONT  VARCHAR2(200)  NULL , --도메인설명내용
    DATATYPE_TPCD     CHAR(2)  NOT NULL , --데이터타입 구분코드(CHAR,VARCHAR2,NUMBER,DATE,TIMESTAMP,BLOB,CLOB,LONG)
    DOMAIN_SIZE   NUMBER(4)  NULL , --도메인크기
    DOMAIN_SCALE      NUMBER(2)  NULL , --도메인정확도
    NN_YN         CHAR(1)  NULL , -- NOT NULL 여부
    USE_YN        CHAR(1)  NOT NULL ,
    STDZ_REG_TPCD     CHAR(1)  NULL ,
    STDZ_PROC_TPCD    CHAR(1)  NOT NULL ,
    REG_TM        VARCHAR2(14)  NOT NULL ,
    REGT_NM       VARCHAR2(50)  NOT NULL ,
    PROC_TM       VARCHAR2(14)  NULL ,
    PROCR_NM      VARCHAR2(50)  NULL ,
    ERR_CONT      VARCHAR2(500)  NULL
);


CREATE UNIQUE INDEX CC_DOMAIN_REG_TC_PK ON CC_DOMAIN_REG_TC
    (DOMAIN_ID  ASC,DOMAIN_SEQNO  ASC);

ALTER TABLE CC_DOMAIN_REG_TC
    ADD CONSTRAINT  CC_DOMAIN_REG_TC_PK PRIMARY KEY (DOMAIN_ID,DOMAIN_SEQNO);

CREATE INDEX CC_DOMAIN_REG_TC_IX1 ON CC_DOMAIN_REG_TC
    (DOMAIN_NM  ASC,DOMAIN_SEQNO  ASC);

CREATE TABLE CC_DOMAIN_TC
(
    DOMAIN_ID     VARCHAR2(10)  NOT NULL , -- id
    DOMAIN_NM     VARCHAR2(50)  NOT NULL , -- 이름
    DOMAIN_DESC_CONT  VARCHAR2(200)  NULL , -- 설명
    DATATYPE_TPCD     CHAR(2)  NOT NULL , -- 타입
    DOMAIN_SIZE   NUMBER(4)  NULL , -- 길이
    DOMAIN_SCALE      NUMBER(2)  NULL , -- 정확도?
    NN_YN         CHAR(1)  NULL , -- 널어블
    USE_YN        CHAR(1)  NOT NULL , -- 사용
    MODF_TM       VARCHAR2(14)  NOT NULL , -- 수정 일시
    MODFR_NM      VARCHAR2(50)  NOT NULL -- 수정자명
);
CREATE UNIQUE INDEX CC_DOMAIN_TC_PK ON CC_DOMAIN_TC
    (DOMAIN_ID  ASC);

ALTER TABLE CC_DOMAIN_TC
    ADD CONSTRAINT  CC_DOMAIN_TC_PK PRIMARY KEY (DOMAIN_ID);

CREATE UNIQUE INDEX CC_DOMAIN_TC_IX1 ON CC_DOMAIN_TC
    (DOMAIN_NM  ASC);

CREATE TABLE CC_WORD_REG_TC
(
    ENG_WORD_NM   VARCHAR2(10)  NOT NULL , --영어단어명
    WORD_SEQNO    NUMBER(3)  NOT NULL , --단어 일련번호
    WORD_TPCD     CHAR(1)  NULL , -- 단어구분코드(기본단어,분류단어)
    WORD_NM       VARCHAR2(50)  NOT NULL , -- 단어명
    ENG_ORG_WORD_NM   VARCHAR2(50)  NOT NULL , -- 영어원문단어명
    USE_YN        CHAR(1)  NOT NULL ,
    STDZ_REG_TPCD     CHAR(1)  NULL ,
    STDZ_PROC_TPCD    CHAR(1)  NOT NULL ,
    REG_TM        VARCHAR2(14)  NOT NULL ,
    REGT_NM       VARCHAR2(50)  NOT NULL ,
    PROC_TM       VARCHAR2(14)  NULL ,
    PROCR_NM      VARCHAR2(50)  NULL ,
    ERR_CONT      VARCHAR2(500)  NULL
);

CREATE UNIQUE INDEX CC_WORD_REG_TC_PK ON CC_WORD_REG_TC
    (ENG_WORD_NM  ASC,WORD_SEQNO  ASC);

ALTER TABLE CC_WORD_REG_TC
    ADD CONSTRAINT  CC_WORD_REG_TC_PK PRIMARY KEY (ENG_WORD_NM,WORD_SEQNO);

CREATE TABLE CC_WORD_TC
(
    ENG_WORD_NM   VARCHAR2(10)  NOT NULL , -- 영어단어명
    WORD_TPCD     CHAR(1)  NULL , -- 단어 구분 코드
    WORD_NM       VARCHAR2(50)  NOT NULL , -- 단어명
    ENG_ORG_WORD_NM   VARCHAR2(50)  NOT NULL , -- 영어원문 단어명
    USE_YN        CHAR(1)  NOT NULL , -- 유저 사용여부
    MODF_TM       VARCHAR2(14)  NOT NULL ,
    MODFR_NM      VARCHAR2(50)  NULL
);

CREATE UNIQUE INDEX CC_WORD_TC_PK ON CC_WORD_TC
    (ENG_WORD_NM  ASC);

ALTER TABLE CC_WORD_TC
    ADD CONSTRAINT  CC_WORD_TC_PK PRIMARY KEY (ENG_WORD_NM);

CREATE INDEX CC_WORD_TC_IX1 ON CC_WORD_TC
    (WORD_NM  ASC);


ALTER TABLE CC_CMCD_REG_TC
    ADD (CONSTRAINT  CC_CMCD_REG_TC_FK2 FOREIGN KEY (HIGH_DICT_SEQNO,HIGH_ENG_DICT_NM,HIGH_CD_VALUE,HIGH_CD_SEQNO) REFERENCES CC_CMCD_REG_TC(DICT_SEQNO,ENG_DICT_NM,CD_VALUE,CD_SEQNO) ON DELETE SET NULL);

ALTER TABLE CC_CMCD_REG_TC
    ADD (CONSTRAINT  CC_CMCD_REG_TC_FK1 FOREIGN KEY (ENG_DICT_NM,DICT_SEQNO) REFERENCES CC_DICT_REG_TC(ENG_DICT_NM,DICT_SEQNO));

ALTER TABLE CC_CMCD_TC
    ADD (CONSTRAINT  CC_CMCD_TC_FK1 FOREIGN KEY (ENG_DICT_NM) REFERENCES CC_DICT_TC(ENG_DICT_NM));

ALTER TABLE CC_CMCD_TC
    ADD (CONSTRAINT  CC_CMCD_TC_FK1 FOREIGN KEY (HIGH_ENG_DICT_NM,HIGH_CD_VALUE) REFERENCES CC_CMCD_TC(ENG_DICT_NM,CD_VALUE) ON DELETE SET NULL);

ALTER TABLE CC_DICT_REG_TC
    ADD (CONSTRAINT  CC_DICT_REG_TC_FK1 FOREIGN KEY (DOMAIN_ID,DOMAIN_SEQNO) REFERENCES CC_DOMAIN_REG_TC(DOMAIN_ID,DOMAIN_SEQNO));

ALTER TABLE CC_DICT_TC
    ADD (CONSTRAINT  CC_DICT_TC_FK1 FOREIGN KEY (DOMAIN_ID) REFERENCES CC_DOMAIN_TC(DOMAIN_ID));